export const LOCATION_OPTIONS = [
  "Remote",
  "Atlanta, GA",
  "Austin, TX",
  "Birmingham, AL",
  "Boston, MA",
  "Charlotte, NC",
  "Chattanooga, TN",
  "Chicago, IL",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Dallas, TX",
  "Denver, CO",
  "Detroit, MI",
  "Franklin, TN",
  "Houston, TX",
  "Huntsville, AL",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "Knoxville, TN",
  "Los Angeles, CA",
  "Louisville, KY",
  "Memphis, TN",
  "Miami, FL",
  "Murfreesboro, TN",
  "Nashville, TN",
  "New York, NY",
  "Orlando, FL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pittsburgh, PA",
  "Raleigh, NC",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "Seattle, WA",
  "St. Louis, MO",
  "Tampa, FL",
  "Washington, DC",
] as const;
