export const MAJOR_OPTIONS = [
  "Accounting",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Business",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agricultural Science",
  "American Studies",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Architecture",
  "Art Education",
  "Art History",
  "Artificial Intelligence",
  "Astronomy",
  "Athletic Training",
  "Automotive Engineering",
  "Aviation Management",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Broadcast Journalism",
  "Business Administration",
  "Business Analytics",
  "Chemical Engineering",
  "Chemistry",
  "Child Development",
  "Civil Engineering",
  "Classics",
  "Clinical Laboratory Science",
  "Cognitive Science",
  "Communications",
  "Community Health",
  "Computer Engineering",
  "Computer Information Systems",
  "Computer Science",
  "Construction Engineering",
  "Construction Management",
  "Criminal Justice",
  "Cybersecurity",
  "Data Analytics",
  "Data Science",
  "Dental Hygiene",
  "Digital Media",
  "Early Childhood Education",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electrical Engineering Technology",
  "Electromechanical Engineering Technology",
  "Elementary Education",
  "Emergency Management",
  "Energy Engineering",
  "Engineering Management",
  "Engineering Physics",
  "English",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Health",
  "Environmental Science",
  "Exercise Science",
  "Fashion Design",
  "Film and Media Production",
  "Finance",
  "Food Science",
  "Forensic Science",
  "Forestry",
  "Game Design",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Administration",
  "Health Informatics",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Resources Management",
  "Human Services",
  "Industrial Design",
  "Industrial Engineering",
  "Industrial Engineering Technology",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Legal Studies",
  "Liberal Arts",
  "Linguistics",
  "Logistics and Supply Chain Management",
  "Management",
  "Management Information Systems",
  "Manufacturing Engineering",
  "Marine Biology",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanical Engineering Technology",
  "Mechatronics Engineering",
  "Media Studies",
  "Medical Laboratory Science",
  "Microbiology",
  "Middle Grades Education",
  "Molecular Biology",
  "Music",
  "Music Business",
  "Network Engineering",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition and Dietetics",
  "Occupational Health and Safety",
  "Operations Management",
  "Organizational Leadership",
  "Petroleum Engineering",
  "Pharmaceutical Sciences",
  "Philosophy",
  "Photography",
  "Physics",
  "Political Science",
  "Pre-Dentistry",
  "Pre-Law",
  "Pre-Medicine",
  "Product Design",
  "Professional Writing",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Relations",
  "Radiologic Science",
  "Real Estate",
  "Recreation and Sport Management",
  "Respiratory Therapy",
  "Robotics Engineering",
  "Secondary Education",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Special Education",
  "Sport Management",
  "Statistics",
  "Supply Chain Management",
  "Sustainability Studies",
  "Systems Engineering",
  "Technical Communication",
  "Theatre",
  "Tourism Management",
  "Urban and Regional Planning",
  "User Experience Design",
  "Veterinary Science",
  "Web Development",
  "Wildlife and Fisheries Science",
] as const;
