export const SKILL_OPTIONS = [
  "3D Modeling",
  "Accounting",
  "Active Listening",
  "Adobe After Effects",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Photoshop",
  "Agile Methodologies",
  "AI Prompt Engineering",
  "ArcGIS",
  "API Development",
  "Assembly",
  "AutoCAD",
  "Automation",
  "AWS",
  "Azure",
  "BIM",
  "Blueprint Reading",
  "Bookkeeping",
  "Budgeting",
  "Business Analysis",
  "Business Development",
  "C",
  "C#",
  "C++",
  "CAD",
  "Canva",
  "Change Management",
  "Chemical Analysis",
  "CI/CD",
  "Civil 3D",
  "Cloud Computing",
  "CNC Machining",
  "Communication",
  "Compliance Management",
  "Computer-Aided Manufacturing",
  "Conflict Resolution",
  "Construction Management",
  "Content Creation",
  "Content Strategy",
  "Continuous Improvement",
  "Contract Management",
  "Cost Estimation",
  "CRM Software",
  "CSS",
  "Customer Relationship Management",
  "Customer Service",
  "Cybersecurity",
  "Data Analysis",
  "Data Engineering",
  "Data Entry",
  "Data Governance",
  "Data Modeling",
  "Data Visualization",
  "Database Administration",
  "Database Management",
  "Debugging",
  "Digital Marketing",
  "Docker",
  "Drafting",
  "Electrical Design",
  "Electrical Troubleshooting",
  "Electronics",
  "Embedded Systems",
  "Employee Relations",
  "Equipment Maintenance",
  "ERP Systems",
  "ETL Development",
  "Event Planning",
  "Excel",
  "Figma",
  "Finite Element Analysis",
  "Financial Analysis",
  "Financial Modeling",
  "Financial Reporting",
  "Forecasting",
  "Forklift Operation",
  "Fundraising",
  "GD&T",
  "Git",
  "Go",
  "Google Analytics",
  "Google Cloud Platform",
  "Google Workspace",
  "Grant Writing",
  "Graphic Design",
  "HTML",
  "Human Resources",
  "HVAC Systems",
  "Inventory Management",
  "Java",
  "JavaScript",
  "Jira",
  "Kotlin",
  "Laboratory Safety",
  "Leadership",
  "Lean Manufacturing",
  "Linux",
  "Logistics",
  "Machine Learning",
  "Machining",
  "Maintenance Planning",
  "Market Research",
  "Marketing Strategy",
  "MATLAB",
  "Mechanical Design",
  "Microsoft Access",
  "Microsoft Excel",
  "Microsoft Office",
  "Microsoft PowerPoint",
  "Microsoft Project",
  "Microsoft Word",
  "MongoDB",
  "Network Administration",
  "Network Security",
  "Node.js",
  "NoSQL",
  "Operations Management",
  "Oracle Database",
  "OSHA Compliance",
  "PCB Design",
  "Performance Management",
  "PLC Programming",
  "PostgreSQL",
  "Power BI",
  "Preventive Maintenance",
  "Primavera P6",
  "Problem Solving",
  "Process Engineering",
  "Process Improvement",
  "Procurement",
  "Product Design",
  "Product Management",
  "Production Planning",
  "Project Coordination",
  "Project Management",
  "Python",
  "Quality Assurance",
  "Quality Control",
  "R",
  "React",
  "Recruiting",
  "Regulatory Compliance",
  "Research",
  "Risk Management",
  "Robotics",
  "Root Cause Analysis",
  "Ruby",
  "Sales",
  "Salesforce",
  "SAP",
  "Scheduling",
  "Search Engine Optimization",
  "Shell Scripting",
  "Six Sigma",
  "SketchUp",
  "Social Media Management",
  "Software Testing",
  "SolidWorks",
  "SQL",
  "Statistical Analysis",
  "Strategic Planning",
  "Supply Chain Management",
  "Surveying",
  "Tableau",
  "Team Building",
  "Teamwork",
  "Technical Support",
  "Technical Writing",
  "TensorFlow",
  "Time Management",
  "Training and Development",
  "Troubleshooting",
  "TypeScript",
  "UI Design",
  "Unity",
  "Unix",
  "User Experience Design",
  "Vendor Management",
  "Video Editing",
  "Visual Basic",
  "Welding",
  "Workplace Safety",
  "Writing and Editing",
] as const;
